"""empty message

Revision ID: 1526d09d0f6f
Revises: 3b37bbdacae4
Create Date: 2024-01-02 11:18:03.229880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1526d09d0f6f'
down_revision: Union[str, None] = '3b37bbdacae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.create_foreign_key('external_users_user_fk', 'external_users', 'users', ['user_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('external_users_user_fk', 'external_users', type_='foreignkey')
    # ### end Alembic commands ###
