"""add external users

Revision ID: 2995e8d08b1f
Revises: 3729b62f6c1f
Create Date: 2023-11-15 11:05:41.861269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2995e8d08b1f"
down_revision: Union[str, None] = "3729b62f6c1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_users",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=256), nullable=False),
        sa.Column(
            "roles",
            sa.ARRAY(sa.VARCHAR(length=64)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_users_email"), "external_users", ["email"], unique=True
    )
    op.create_table(
        "native_users",
        sa.Column("name", sa.VARCHAR(length=256), nullable=False),
        sa.Column(
            "roles",
            sa.ARRAY(sa.VARCHAR(length=64)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=256), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_native_users_email"), "native_users", ["email"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_native_users_email"), table_name="native_users")
    op.drop_table("native_users")
    op.drop_index(op.f("ix_external_users_email"), table_name="external_users")
    op.drop_table("external_users")
    # ### end Alembic commands ###
