"""empty message

Revision ID: 30fae31e287b
Revises: 03ce479e3d0b
Create Date: 2024-01-03 17:04:28.782449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30fae31e287b"
down_revision: Union[str, None] = "03ce479e3d0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_credentials",
        "password_hash",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    op.alter_column(
        "user_credentials",
        "provider",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_credentials",
        "provider",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "user_credentials",
        "password_hash",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )

    # ### end Alembic commands ###
