"""move name to AbstractUser 3

Revision ID: 3b37bbdacae4
Revises: 031748086000
Create Date: 2023-11-16 11:14:41.617731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b37bbdacae4"
down_revision: Union[str, None] = "031748086000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experimental_plans",
        "researcher_email",
        existing_type=postgresql.CITEXT(),
        type_=postgresql.DOMAIN("email", sa.VARCHAR(length=256)),
        existing_nullable=False,
    )
    op.alter_column(
        "experimental_plans",
        "supervisor_email",
        existing_type=postgresql.CITEXT(),
        type_=postgresql.DOMAIN("email", sa.VARCHAR(length=256)),
        existing_nullable=True,
    )
    op.alter_column(
        "external_users",
        "email",
        existing_type=postgresql.CITEXT(),
        type_=postgresql.DOMAIN("email", sa.VARCHAR(length=256)),
        existing_nullable=False,
    )
    op.alter_column(
        "native_users",
        "email",
        existing_type=postgresql.CITEXT(),
        type_=postgresql.DOMAIN("email", sa.VARCHAR(length=256)),
        existing_nullable=False,
    )
    op.alter_column(
        "work_units",
        "technician_email",
        existing_type=postgresql.CITEXT(),
        type_=postgresql.DOMAIN("email", sa.VARCHAR(length=256)),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_units",
        "technician_email",
        existing_type=postgresql.DOMAIN("email", sa.VARCHAR(length=256)),
        type_=postgresql.CITEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "native_users",
        "email",
        existing_type=postgresql.DOMAIN("email", sa.VARCHAR(length=256)),
        type_=postgresql.CITEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "external_users",
        "email",
        existing_type=postgresql.DOMAIN("email", sa.VARCHAR(length=256)),
        type_=postgresql.CITEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "experimental_plans",
        "supervisor_email",
        existing_type=postgresql.DOMAIN("email", sa.VARCHAR(length=256)),
        type_=postgresql.CITEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "experimental_plans",
        "researcher_email",
        existing_type=postgresql.DOMAIN("email", sa.VARCHAR(length=256)),
        type_=postgresql.CITEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
