"""empty message

Revision ID: e8a73af8e1ef
Revises: 30fae31e287b
Create Date: 2024-01-05 16:05:02.432735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e8a73af8e1ef"
down_revision: Union[str, None] = "30fae31e287b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_campuses_code"), "campuses", ["code"], unique=True)
    op.create_index(op.f("ix_campuses_name"), "campuses", ["name"], unique=True)

    op.add_column("users", sa.Column("campus_id", sa.UUID(), nullable=True))
    op.create_foreign_key("user_campus_fk", "users", "campuses", ["campus_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint("user_campus_fk", "users", type_="foreignkey")
    op.drop_column("users", "campus_id")

    op.drop_index(op.f("ix_campuses_name"), table_name="campuses")
    op.drop_index(op.f("ix_campuses_code"), table_name="campuses")
    # ### end Alembic commands ###
