
services:
  api:
    build: './src/api'
    ports:
      - "8000:8000"

  postgres:
    image: "postgres:15.4"
    environment:
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  pgdata: {}
