services:
  app:
    build: './app'
    image: ghcr.io/cqueng/lab-requests-app
    volumes:
      - "ng_build_cache:/home/node/.angular/cache:rw"

    ports:
      - "4200:4200"

  api:
    build:
      context: './api'
      args:
        NG_VERSION: ${NG_VERSION}
    image: ghcr.io/cqueng/lab-requests-api
    init: true
    ports:
      - "8000:8000"
      - "8765:8765"
    environment:
      API_DEBUG: ${API_DEBUG}
      DB_HOST: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      FILESTORE_PROVIDER: 'local'
      FILESTORE_KEY: /srv/files
    volumes:
      - 'lab_work_attachments:/srv/files/lab/work-units:rw'

  postgres:
    build: './postgres'
    image: ghcr.io/cqueng/lab-requests-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "pgdata:/var/lib/postgresql"
    ports:
      - "5432:5432"
    restart: "on-failure"

  pg-admin:
    image: "dpage/pgadmin4:8"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'tom@ovangle.com'
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
      - "./postgres/pgadmin/servers.json:/pgadmin4/servers.json:rw"
    ports:
      - "5433:80"

volumes:
  pgdata: {}
  pgadmin_data: {}
  lab_work_attachments: {}
  ng_build_cache: {}
