version: "3"
services:
  app:
    build: './app'
    ports:
      - "4201:4200"
    profiles:
    - do_not_start

  api:
    build: './api'
    ports:
      - "8000:8000"
      - "8765:8765"
    environment:
      DB_HOST: postgres
      DB_PASSWORD: secret
      API_DEBUG: yes
    volumes:
      - './api:/srv/api'

  postgres:
    build: './postgres'
    environment:
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: "on-failure"

  pg_admin:
    image: "dpage/pgadmin4:7"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'tom@ovangle.com'
      PGADMIN_DEFAULT_PASSWORD: 'secret'
    ports:
      - "5433:80"

      

volumes:
  pgdata: {}
