version: "3"
services:
  app:
    build: './app'
    image: ghcr.io/cqueng/lab-requests-app
    command: npm run start
    ports:
      - "4200:4200"
    profiles:
      # preferable to disable the app server locally and run `ng serve` on the host.
      - do_not_start

  api:
    build: './api'
    image: ghcr.io/cqueng/lab-requests-api
    ports:
      - "8000:8000"
      - "8765:8765"
    environment:
      DB_HOST: postgres
      DB_PASSWORD: secret
      API_DEBUG: 'yes'
    volumes:
      - './api:/srv/api'
      - 'lab_work_attachments:/srv/files/lab/work-units:rw'

  filesrv:
    image: nginx:1.25
    volumes:
      - './filesrv/nginx.conf:/etc/nginx/nginx.conf:ro'
      - 'lab_work_attachments:/srv/files/lab/work-units:ro'
    ports:
      - "6767:80"

  postgres:
    build: './postgres'
    image: ghcr.io/cqueng/lab-requests-postgres
    environment:
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - "pgdata:/var/lib/postgresql"
    ports:
      - "5432:5432"
    restart: "on-failure"

  pg-admin:
    image: "dpage/pgadmin4:7"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'tom@ovangle.com'
      PGADMIN_DEFAULT_PASSWORD: 'secret'
    ports:
      - "5433:80"

volumes:
  pgdata: {}
  lab_work_attachments: {}
