"""empty message

Revision ID: 75f4b6c6325f
Revises: 7ffee92afd08
Create Date: 2023-11-16 12:51:40.814074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75f4b6c6325f'
down_revision: Union[str, None] = '7ffee92afd08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'email',
               existing_type=postgresql.CITEXT(),
               type_=postgresql.DOMAIN('email', CITEXT()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'email',
               existing_type=postgresql.DOMAIN('email', CITEXT()),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
