"""empty message

Revision ID: 7ffee92afd08
Revises: 
Create Date: 2023-11-16 12:29:16.139531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ffee92afd08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from models import _POSTGRES_EMAIL_RE

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column(
        'email', 
        postgresql.DOMAIN('email', postgresql.CITEXT(), check='value ~ \'{_POSTGRES_EMAIL_RE}\''), 
        nullable=False
    ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
    op.execute('DROP DOMAIN email')
