apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "4201"
      port: 4201
      targetPort: 4200
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
