apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "public-static-ip"
    networking.gke.io/managed-certificates: 'public-ingress-certificate'
    kubernetes.io/ingress.class: 'gce'
spec:
  rules:
  - http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: api
            port: 
              number: 8000
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: app
            port:
              number: 3000

          
