"""empty message

Revision ID: 03ff78674e24
Revises: 126a036fe649
Create Date: 2024-09-13 12:40:44.398282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from db.models.research.plan import ResearchPlan
from db.models.uni.discipline import DISCIPLINE_ENUM

# revision identifiers, used by Alembic.
revision: str = '03ff78674e24'
down_revision: Union[str, None] = '126a036fe649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    DISCIPLINE_ENUM.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('disciplines', postgresql.ARRAY(postgresql.ENUM(name='uni_discipline')), server_default='{}', nullable=False))
    op.add_column('research_plan', sa.Column('discipline_two', postgresql.ENUM(name='uni_discipline'), nullable=False))

    update_q = sa.update(ResearchPlan).values(
        discipline_two=ResearchPlan.discipline
    )
    print(update_q)
    op.execute(update_q)

    op.drop_column('research_plan', 'discipline')
    op.alter_column('research_plan', 'discipline_two', new_column_name='discipline')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_plan', 'discipline_two')
    op.drop_column('equipment', 'disciplines')
    # ### end Alembic commands ###
