"""add equipment installation field to equipment lease

Revision ID: 07ce69b49757
Revises: f1bab4f5d6ac
Create Date: 2024-04-22 15:20:02.626819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ce69b49757'
down_revision: Union[str, None] = 'f1bab4f5d6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_resource__equipment_lease', sa.Column('equipment_installation_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'lab_resource__equipment_lease', 'lab_equipment_installation', ['equipment_installation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_resource__equipment_lease', type_='foreignkey')
    op.drop_column('lab_resource__equipment_lease', 'equipment_installation_id')
    # ### end Alembic commands ###
