"""empty message

Revision ID: 0fb112631e59
Revises: aa440f34497d
Create Date: 2024-03-04 00:49:46.321426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from db.models.research.plan import ResearchPlan
from db.models.lab import Lab


# revision identifiers, used by Alembic.
revision: str = "0fb112631e59"
down_revision: Union[str, None] = "aa440f34497d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("research_plan", sa.Column("lab_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "research_plan_lab_fk", "research_plan", "lab", ["lab_id"], ["id"]
    )
    session = orm.Session(bind=op.get_bind())

    for plan in session.scalars(sa.select(ResearchPlan)):
        researcher = plan.researcher
        default_lab = session.scalar(
            sa.select(Lab).where(
                Lab.discipline == researcher.primary_discipline,
                Lab.campus_id == researcher.campus_id,
            )
        )
        if default_lab is None:
            raise ValueError(
                f"Could not determine default lab for researcher {researcher.id}"
            )
        plan.lab_id = default_lab.id
        session.add(plan)
    session.commit()

    op.alter_column("research_plan", "lab_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("research_plan_lab_fk", "research_plan", type_="foreignkey")
    op.drop_column("research_plan", "lab_id")
    # ### end Alembic commands ###
