"""empty message

Revision ID: 126a036fe649
Revises: 4ca536e7c741
Create Date: 2024-09-13 11:26:31.720612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126a036fe649'
down_revision: Union[str, None] = '4ca536e7c741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment_installation', 'installed_model_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment_installation', 'installed_model_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
