"""empty message

Revision ID: 2b5ec29579ee
Revises: f4ddb68f0f59
Create Date: 2024-02-21 15:35:58.175413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5ec29579ee'
down_revision: Union[str, None] = 'f4ddb68f0f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_equipment_installation', sa.Column('replaces_installation_id', sa.UUID(), nullable=True))
    op.drop_constraint('lab_equipment_installation_current_install_id_fkey', 'lab_equipment_installation', type_='foreignkey')
    op.create_foreign_key(None, 'lab_equipment_installation', 'lab_equipment_installation', ['replaces_installation_id'], ['id'])
    op.drop_column('lab_equipment_installation', 'current_install_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_equipment_installation', sa.Column('current_install_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lab_equipment_installation', type_='foreignkey')
    op.create_foreign_key('lab_equipment_installation_current_install_id_fkey', 'lab_equipment_installation', 'lab_equipment_installation', ['current_install_id'], ['id'])
    op.drop_column('lab_equipment_installation', 'replaces_installation_id')
    # ### end Alembic commands ###
