"""empty message

Revision ID: 3e5ae9afc9ef
Revises: 0fb112631e59
Create Date: 2024-03-04 02:49:54.898646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5ae9afc9ef'
down_revision: Union[str, None] = '0fb112631e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_plan_task', 'allocated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_plan_task', sa.Column('allocated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
