"""empty message

Revision ID: 4ca536e7c741
Revises: b06bd7020c62
Create Date: 2024-09-13 11:18:22.462498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db import LocalSession
from db.models.equipment.equipment_installation import EquipmentInstallation


# revision identifiers, used by Alembic.
revision: str = '4ca536e7c741'
down_revision: Union[str, None] = 'b06bd7020c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_installation', sa.Column('installed_model_name', sa.TEXT(), nullable=True, default=''))

    op.execute(sa.update(EquipmentInstallation).values(installed_model_name=''))

    op.drop_column('equipment_installation', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_installation', sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('equipment_installation', 'installed_model_name')
    # ### end Alembic commands ###
