"""fix_provision_problems

Revision ID: 581ddc69e4b9
Revises: 8fc5fb69a16b
Create Date: 2024-09-22 15:47:11.299037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '581ddc69e4b9'
down_revision: Union[str, None] = '8fc5fb69a16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_installation_provision', 'quantity_required')
    op.add_column('lab_provision', sa.Column('action_params', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('lab_provision', sa.Column('purchase_url', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('lab_provision', sa.Column('purchase_instructions', sa.TEXT(), nullable=False))
    op.alter_column('lab_provision', 'budget_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lab_provision', 'budget_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('lab_provision', 'purchase_instructions')
    op.drop_column('lab_provision', 'purchase_url')
    op.drop_column('lab_provision', 'action_params')
    op.add_column('equipment_installation_provision', sa.Column('quantity_required', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
