"""empty message

Revision ID: 5d5d57d6e69c
Revises: c3db42db9f7b
Create Date: 2024-09-18 14:15:51.778936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d5d57d6e69c'
down_revision: Union[str, None] = 'c3db42db9f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_plan', 'discipline',
               existing_type=postgresql.ENUM('ICT', 'ELECTRICAL', 'CIVIL', 'MECHANICAL', name='discipline'),
               type_=postgresql.ENUM(name='uni_discipline'),
               postgresql_using='discipline::VARCHAR::uni_discipline',
               existing_nullable=False)
    op.drop_column('research_plan', 'discipline_two')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_plan', sa.Column('discipline_two', postgresql.ENUM(name='uni_discipline'), autoincrement=False, nullable=False))
    op.alter_column('research_plan', 'discipline',
               existing_type=postgresql.ENUM(name='uni_discipline'),
               type_=postgresql.ENUM('ICT', 'ELECTRICAL', 'CIVIL', 'MECHANICAL', name='discipline'),
               existing_nullable=False)
    # ### end Alembic commands ###
