"""empty message

Revision ID: 644950c52ab7
Revises: 6fa5080e5f64
Create Date: 2024-09-26 21:54:22.692608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644950c52ab7'
down_revision: Union[str, None] = '6fa5080e5f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('packaged_software_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'software', ['packaged_software_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'packaged_software_id')
    # ### end Alembic commands ###
