"""empty message

Revision ID: 7b728bde8c9e
Revises: 
Create Date: 2024-02-19 13:10:34.953115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b728bde8c9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_equipment_provision', sa.Column('reason', sa.TEXT(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_equipment_provision', 'reason')
    # ### end Alembic commands ###
