"""empty message

Revision ID: 7ceba5815034
Revises: 5d5d57d6e69c
Create Date: 2024-09-18 14:21:08.242325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ceba5815034'
down_revision: Union[str, None] = '5d5d57d6e69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('equipment_installation_updated_by_id_fkey', 'equipment_installation', type_='foreignkey')
    op.drop_constraint('equipment_installation_created_by_id_fkey', 'equipment_installation', type_='foreignkey')
    op.drop_column('equipment_installation', 'updated_by_id')
    op.drop_column('equipment_installation', 'created_by_id')
    op.add_column('lab_installation', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lab_installation', 'user', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'lab_installation', type_='foreignkey')
    op.drop_column('lab_installation', 'updated_by_id')
    op.add_column('equipment_installation', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('equipment_installation', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('equipment_installation_created_by_id_fkey', 'equipment_installation', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key('equipment_installation_updated_by_id_fkey', 'equipment_installation', 'user', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###
