"""lowercase research funding names

Revision ID: 8fc5fb69a16b
Revises: 4f558295bb9b
Create Date: 2024-09-21 14:53:40.442934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

from db.models.uni.funding import Funding


# revision identifiers, used by Alembic.
revision: str = '8fc5fb69a16b'
down_revision: Union[str, None] = '4f558295bb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.execute(
        sa.update(Funding).values(name = func.lower(Funding.name))
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
