"""empty message

Revision ID: b06bd7020c62
Revises: e0d7989ab402
Create Date: 2024-09-12 21:44:25.395719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06bd7020c62'
down_revision: Union[str, None] = 'e0d7989ab402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_installation', sa.Column('created_by_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'lab_installation', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_installation', type_='foreignkey')
    op.drop_column('lab_installation', 'created_by_id')
    # ### end Alembic commands ###
