"""empty message

Revision ID: c189e69a8342
Revises: 42e5608e160c
Create Date: 2024-04-10 06:56:15.925842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c189e69a8342'
down_revision: Union[str, None] = '42e5608e160c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_resource_container',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lab_resource', sa.Column('container_id', sa.Uuid(), nullable=False))
    op.add_column('lab_resource', sa.Column('index', sa.Integer(), nullable=False))
    op.add_column('research_plan', sa.Column('container_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'research_plan', 'lab_resource_container', ['container_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_plan', type_='foreignkey')
    op.drop_column('research_plan', 'container_id')
    op.drop_column('lab_resource', 'index')
    op.drop_column('lab_resource', 'container_id')
    op.drop_table('lab_resource_container')
    # ### end Alembic commands ###
