"""empty message

Revision ID: c3db42db9f7b
Revises: 03ff78674e24
Create Date: 2024-09-18 14:11:59.153755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3db42db9f7b'
down_revision: Union[str, None] = '03ff78674e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_installation', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('equipment_installation', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'equipment_installation', 'user', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'equipment_installation', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'equipment_installation', type_='foreignkey')
    #op.drop_constraint(None, 'equipment_installation', type_='foreignkey')
    #op.drop_column('equipment_installation', 'updated_by_id')
    #op.drop_column('equipment_installation', 'created_by_id')
    # ### end Alembic commands ###
    pass
