"""empty message

Revision ID: c798de283765
Revises: 7ceba5815034
Create Date: 2024-09-19 22:38:16.237423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c798de283765'
down_revision: Union[str, None] = '7ceba5815034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_budget', sa.Column('lab_id', sa.UUID(), nullable=True))
    op.add_column('research_budget', sa.Column('research_plan_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'research_budget', 'research_plan', ['research_plan_id'], ['id'])
    op.create_foreign_key(None, 'research_budget', 'lab', ['lab_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_budget', type_='foreignkey')
    op.drop_constraint(None, 'research_budget', type_='foreignkey')
    op.drop_column('research_budget', 'research_plan_id')
    op.drop_column('research_budget', 'lab_id')
    # ### end Alembic commands ###
