"""empty message

Revision ID: c9ac84bbdab5
Revises: 62d7bfa4b366
Create Date: 2024-04-19 11:51:12.726960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c9ac84bbdab5"
down_revision: Union[str, None] = "62d7bfa4b366"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab_resource__equipment_lease",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("equipment_id", sa.UUID(), nullable=False),
        sa.Column("equipment_provision_id", sa.UUID(), nullable=True),
        sa.Column("start_date", postgresql.TIME(timezone=True), nullable=True),
        sa.Column("end_date", postgresql.TIME(timezone=True), nullable=True),
        sa.Column(
            "equipment_training_completed",
            postgresql.ARRAY(sa.TEXT()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("require_supervision", sa.BOOLEAN(), nullable=False),
        sa.Column("setup_instructions", sa.TEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["lab_equipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["equipment_provision_id"],
            ["lab_equipment_provision.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["lab_resource.id"], name="equipment_lease_resource_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("lab_equipment_lease")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab_equipment_lease",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("equipment_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "equipment_provision_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "start_date",
            postgresql.TIME(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "end_date",
            postgresql.TIME(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "equipment_training_completed",
            postgresql.ARRAY(sa.TEXT()),
            server_default=sa.text("'{}'::text[]"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "require_supervision", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column("setup_instructions", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["lab_equipment.id"],
            name="lab_equipment_lease_equipment_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["equipment_provision_id"],
            ["lab_equipment_provision.id"],
            name="lab_equipment_lease_equipment_provision_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["lab_resource.id"], name="lab_equipment_lease_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="lab_equipment_lease_pkey"),
    )
    op.drop_table("lab_resource__equipment_lease")
    # ### end Alembic commands ###
