"""2024-01-12 add user discipline

Revision ID: ca78c65c208e
Revises: a69f42d0d33d
Create Date: 2024-01-12 22:44:32.708486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.dialects import postgresql

from db.models import User
from db.seeds import seed_user

# revision identifiers, used by Alembic.
revision: str = "ca78c65c208e"
down_revision: Union[str, None] = "a69f42d0d33d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("title", sa.VARCHAR(length=256), nullable=False, default="")
    )
    op.add_column(
        "user",
        sa.Column(
            "disciplines",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "ICT", "ELECTRICAL", "CIVIL", "MECHANICAL", name="discipline"
                )
            ),
            server_default="{}",
            nullable=False,
        ),
    )

    session = Session(bind=op.get_bind())
    user_df = seed_user.load_user_seeds()

    for user in session.scalars(sa.select(User)):
        print("updating user", user.email)
        user_row = seed_user.get_user_row(user_df, user.email)

        user.title = str(user_row.get("Title")).strip()
        print("Set title", user.title)
        user.disciplines = seed_user.disciplines_from_user_seed_row(user_row)
        print("Set disciplines", user.disciplines)

    session.commit()


def downgrade() -> None:
    op.drop_column("user", "disciplines")
    op.drop_column("user", "title")
