"""empty message

Revision ID: f4ddb68f0f59
Revises: 7b728bde8c9e
Create Date: 2024-02-21 14:16:15.355156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ddb68f0f59'
down_revision: Union[str, None] = '7b728bde8c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_equipment_provision', sa.Column('approved_note', sa.TEXT(), server_default='', nullable=False))
    op.add_column('lab_equipment_provision', sa.Column('purchased_note', sa.TEXT(), server_default='', nullable=False))
    op.add_column('lab_equipment_provision', sa.Column('installed_note', sa.TEXT(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_equipment_provision', 'installed_note')
    op.drop_column('lab_equipment_provision', 'purchased_note')
    op.drop_column('lab_equipment_provision', 'approved_note')
    # ### end Alembic commands ###
